[monitoring]
node01 ansible_host=192.168.56.11 ansible_ssh_private_key_file=../Vagrant/.vagrant/machines/so-lab-node-01/virtualbox/private_key

[workers]
node02 ansible_host=192.168.56.12 ansible_ssh_private_key_file=../Vagrant/.vagrant/machines/so-lab-node-02/virtualbox/private_key

[lab:children]
monitoring
workers

[lab:vars]
ansible_user=vagrant
ansible_become=true
ansible_become_method=sudo
ansible_python_interpreter=/usr/bin/python3